// <auto-generated />
using System;
using CrewCall.Reporting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrewCall.Reporting.Data.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20261008175602_InitialReportingProjections")]
    partial class InitialReportingProjections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrewCall.Reporting.Data.AssignmentActivity", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset?>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<Guid?>("ReplacedByAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_assignment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("AssignmentId");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("ix_assignment_activity_visit");

                    b.HasIndex("TechnicianId", "CreatedAtUtc")
                        .HasDatabaseName("ix_assignment_activity_technician_created_at");

                    b.ToTable("assignment_activity", "reporting", t =>
                        {
                            t.HasCheckConstraint("ck_assignment_activity_status", "status IN ('Active', 'Replaced', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("CrewCall.Reporting.Data.IncidentActivity", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at_utc");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("IncidentId");

                    b.HasIndex("TechnicianId", "DispatchedAtUtc")
                        .HasDatabaseName("ix_incident_activity_technician_dispatched_at");

                    b.ToTable("incident_activity", "reporting");
                });

            modelBuilder.Entity("CrewCall.Reporting.Data.ProjectionCheckpoint", b =>
                {
                    b.Property<string>("ProjectionName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("projection_name");

                    b.Property<DateTimeOffset?>("LastEventOccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_occurred_at_utc");

                    b.Property<DateTimeOffset?>("LastProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_processed_at_utc");

                    b.Property<long>("ProcessedMessages")
                        .HasColumnType("bigint")
                        .HasColumnName("processed_messages");

                    b.HasKey("ProjectionName");

                    b.ToTable("projection_checkpoints", "reporting");
                });

            modelBuilder.Entity("CrewCall.Reporting.Data.ReportingInboxMessage", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consumer_name");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("ConsumerName", "MessageId");

                    b.ToTable("inbox_messages", "reporting", t =>
                        {
                            t.HasCheckConstraint("ck_inbox_messages_consumer_name_not_blank", "btrim(consumer_name) <> ''");
                        });
                });

            modelBuilder.Entity("CrewCall.Reporting.Data.TechnicianActivityDaily", b =>
                {
                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<DateOnly>("DateUtc")
                        .HasColumnType("date")
                        .HasColumnName("date_utc");

                    b.Property<int>("AssignmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_count");

                    b.Property<int>("CompletedVisits")
                        .HasColumnType("integer")
                        .HasColumnName("completed_visits");

                    b.Property<decimal>("GrossWorkMinutes")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("gross_work_minutes");

                    b.Property<int>("IncidentDispatchCount")
                        .HasColumnType("integer")
                        .HasColumnName("incident_dispatch_count");

                    b.Property<decimal>("NetWorkMinutes")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("net_work_minutes");

                    b.Property<decimal>("PauseMinutes")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("pause_minutes");

                    b.Property<decimal>("TravelMinutes")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("travel_minutes");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("TechnicianId", "DateUtc");

                    b.ToTable("technician_activity", "reporting", t =>
                        {
                            t.HasCheckConstraint("ck_technician_activity_counts", "completed_visits >= 0 AND assignment_count >= 0 AND incident_dispatch_count >= 0");

                            t.HasCheckConstraint("ck_technician_activity_minutes", "travel_minutes >= 0 AND gross_work_minutes >= 0 AND pause_minutes >= 0 AND net_work_minutes >= 0");
                        });
                });

            modelBuilder.Entity("CrewCall.Reporting.Data.VisitActivity", b =>
                {
                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<decimal?>("ActualGrossWorkMinutes")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("actual_gross_work_minutes");

                    b.Property<decimal?>("ActualNetWorkMinutes")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("actual_net_work_minutes");

                    b.Property<decimal?>("ActualPauseMinutes")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("actual_pause_minutes");

                    b.Property<decimal?>("ActualTravelMinutes")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("actual_travel_minutes");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<DateTimeOffset?>("PlannedEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_end_utc");

                    b.Property<DateTimeOffset?>("PlannedStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_start_utc");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTimeOffset?>("StatusChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at_utc");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VisitStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visit_status");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.Property<string>("WorkOrderPriority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("work_order_priority");

                    b.HasKey("VisitId");

                    b.HasIndex("SiteId", "PlannedStartUtc")
                        .HasDatabaseName("ix_visit_activity_site_planned_start");

                    b.HasIndex("TechnicianId", "CompletedAtUtc")
                        .HasDatabaseName("ix_visit_activity_technician_completed_at");

                    b.HasIndex("TechnicianId", "PlannedStartUtc")
                        .HasDatabaseName("ix_visit_activity_technician_planned_start");

                    b.ToTable("visit_activity", "reporting");
                });
#pragma warning restore 612, 618
        }
    }
}
