version: "3.9"

services:
  db:
    image: postgres:16
    container_name: roombooking-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres12
      POSTGRES_DB: roombooking
    ports:
      - "5432:5432"
    volumes:
      - roombooking-data:/var/lib/postgresql/data

volumes:
  roombooking-data:
