// <auto-generated />
using System;
using CrewCall.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrewCall.Persistence.Migrations
{
    [DbContext(typeof(CrewCallDbContext))]
    [Migration("20261007175119_AddVisitExecutionWorkflow")]
    partial class AddVisitExecutionWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrewCall.Persistence.Operations.OperationalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aggregate_type");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Sequence"));

                    b.HasKey("Id");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.HasIndex("AggregateType", "AggregateId", "OccurredAtUtc")
                        .HasDatabaseName("ix_operational_events_aggregate");

                    b.ToTable("operational_events", "ops");
                });

            modelBuilder.Entity("CrewCall.Resources.Equipment.EquipmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("asset_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique();

                    b.ToTable("equipment", "resources");
                });

            modelBuilder.Entity("CrewCall.Resources.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("registration_number");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("vehicles", "resources");
                });

            modelBuilder.Entity("CrewCall.Scheduling.Assignments.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ClaimedEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_end");

                    b.Property<DateTimeOffset>("ClaimedStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_start");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("ReplacedByAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_assignment_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<int>("TravelBufferAfterMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("travel_buffer_after_minutes");

                    b.Property<int>("TravelBufferBeforeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("travel_buffer_before_minutes");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id");

                    b.HasIndex("VisitId")
                        .IsUnique()
                        .HasDatabaseName("ux_assignments_one_active_per_visit")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("VisitId", "CreatedAtUtc")
                        .HasDatabaseName("ix_assignments_visit_history");

                    b.ToTable("assignments", "scheduling", t =>
                        {
                            t.HasCheckConstraint("ck_assignments_claimed_window", "claimed_start < claimed_end");

                            t.HasCheckConstraint("ck_assignments_status", "status IN ('Active', 'Replaced', 'Cancelled')");

                            t.HasCheckConstraint("ck_assignments_travel_buffers", "travel_buffer_before_minutes >= 0 AND travel_buffer_after_minutes >= 0");
                        });
                });

            modelBuilder.Entity("CrewCall.Scheduling.Assignments.AssignmentEquipment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.HasKey("AssignmentId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("assignment_equipment", "scheduling");
                });

            modelBuilder.Entity("CrewCall.Scheduling.Reservations.ResourceReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("resource_type");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("VisitId");

                    b.HasIndex("ResourceType", "ResourceId", "Start", "End")
                        .HasDatabaseName("ix_resource_reservations_resource_period");

                    b.ToTable("resource_reservations", "scheduling", t =>
                        {
                            t.HasCheckConstraint("ck_resource_reservations_resource_type", "resource_type IN ('Technician', 'Vehicle', 'Equipment')");

                            t.HasCheckConstraint("ck_resource_reservations_start_before_end", "start_at < end_at");
                        });
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_reference");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("customers", "workorders");
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Executions.VisitExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TravelStartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("travel_started_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<DateTimeOffset?>("WorkStartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("work_started_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("VisitId")
                        .IsUnique()
                        .HasDatabaseName("ux_visit_executions_visit_id");

                    b.ToTable("visit_executions", "workorders", t =>
                        {
                            t.HasCheckConstraint("ck_visit_executions_cancelled_at", "(status = 'Cancelled') = (cancelled_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_visit_executions_completed_at", "(status = 'Completed') = (completed_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_visit_executions_status", "status IN ('NotStarted', 'Traveling', 'Working', 'Paused', 'Completed', 'Cancelled')");

                            t.HasCheckConstraint("ck_visit_executions_travel_before_work", "travel_started_at_utc IS NULL OR work_started_at_utc IS NULL OR travel_started_at_utc <= work_started_at_utc");

                            t.HasCheckConstraint("ck_visit_executions_travel_started", "status <> 'Traveling' OR travel_started_at_utc IS NOT NULL");

                            t.HasCheckConstraint("ck_visit_executions_work_before_completion", "work_started_at_utc IS NULL OR completed_at_utc IS NULL OR work_started_at_utc <= completed_at_utc");

                            t.HasCheckConstraint("ck_visit_executions_work_started", "status NOT IN ('Working', 'Paused', 'Completed') OR work_started_at_utc IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Executions.VisitExecutionPause", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<Guid>("VisitExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_execution_id");

                    b.HasKey("Id");

                    b.HasIndex("VisitExecutionId")
                        .IsUnique()
                        .HasDatabaseName("ux_visit_execution_pauses_one_open")
                        .HasFilter("ended_at_utc IS NULL");

                    b.HasIndex("VisitExecutionId", "StartedAtUtc")
                        .HasDatabaseName("ix_visit_execution_pauses_execution_started");

                    b.ToTable("visit_execution_pauses", "workorders", t =>
                        {
                            t.HasCheckConstraint("ck_visit_execution_pauses_start_before_end", "ended_at_utc IS NULL OR started_at_utc < ended_at_utc");
                        });
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Incidents.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("RequestedEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_end");

                    b.Property<DateTimeOffset>("RequestedStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_start");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_incidents_status");

                    b.HasIndex("WorkOrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_incidents_work_order_id")
                        .HasFilter("work_order_id IS NOT NULL");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_incidents_created_at_utc_id");

                    b.HasIndex("SiteId", "CustomerId");

                    b.ToTable("incidents", "workorders", t =>
                        {
                            t.HasCheckConstraint("ck_incidents_priority", "priority IN ('High', 'Urgent', 'Critical')");

                            t.HasCheckConstraint("ck_incidents_requested_start_before_end", "requested_start < requested_end");

                            t.HasCheckConstraint("ck_incidents_resolved_at_when_resolved", "(status = 'Resolved') = (resolved_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_incidents_status", "status IN ('New', 'Analyzing', 'ReadyForDispatch', 'Dispatched', 'Resolved', 'Cancelled')");

                            t.HasCheckConstraint("ck_incidents_work_order_when_dispatched", "(status IN ('Dispatched', 'Resolved')) = (work_order_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Incidents.IncidentRequiredSkill", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("SkillCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("skill_code");

                    b.HasKey("IncidentId", "SkillCode");

                    b.ToTable("incident_required_skills", "workorders", t =>
                        {
                            t.HasCheckConstraint("ck_incident_required_skills_skill_code_normalized", "skill_code <> '' AND skill_code = upper(btrim(skill_code))");
                        });
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Sites.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line1");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("sites", "workorders", t =>
                        {
                            t.HasCheckConstraint("ck_sites_coordinates_together", "(latitude IS NULL) = (longitude IS NULL)");

                            t.HasCheckConstraint("ck_sites_latitude_range", "latitude IS NULL OR latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_sites_longitude_range", "longitude IS NULL OR longitude BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Visits.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("visits", "workorders", t =>
                        {
                            t.HasCheckConstraint("ck_visits_start_before_end", "start_at < end_at");

                            t.HasCheckConstraint("ck_visits_status", "status IN ('Planned', 'InProgress', 'Completed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("CrewCall.WorkOrders.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SiteId", "CustomerId");

                    b.ToTable("work_orders", "workorders", t =>
                        {
                            t.HasCheckConstraint("ck_work_orders_priority", "priority IN ('Low', 'Normal', 'High', 'Urgent')");

                            t.HasCheckConstraint("ck_work_orders_status", "status IN ('Open', 'Planned', 'InProgress', 'Completed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("CrewCall.Workforce.Absences.TechnicianAbsence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("TechnicianId", "Start", "End");

                    b.ToTable("technician_absences", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_technician_absences_start_before_end", "start_at < end_at");

                            t.HasCheckConstraint("ck_technician_absences_type", "type IN ('Vacation', 'SickLeave', 'Training', 'Other')");
                        });
                });

            modelBuilder.Entity("CrewCall.Workforce.Holidays.HolidayCalendarEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("region_code");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "Date", "RegionCode")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("CountryCode", "Date", "RegionCode"), false);

                    b.ToTable("holiday_calendar", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_holiday_calendar_country_code", "country_code ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_holiday_calendar_region_code", "region_code IS NULL OR region_code ~ '^[A-Z0-9]{1,3}$'");
                        });
                });

            modelBuilder.Entity("CrewCall.Workforce.Skills.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("code IS NOT NULL");

                    b.ToTable("skills", "workforce");
                });

            modelBuilder.Entity("CrewCall.Workforce.Skills.TechnicianSkill", b =>
                {
                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.HasKey("TechnicianId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("technician_skills", "workforce");
                });

            modelBuilder.Entity("CrewCall.Workforce.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("teams", "workforce");
                });

            modelBuilder.Entity("CrewCall.Workforce.Technicians.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("technicians", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_technicians_country_code", "country_code ~ '^[A-Z]{2}$'");
                        });
                });

            modelBuilder.Entity("CrewCall.Workforce.WorkingHours.TechnicianWorkingHours", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndLocalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_local_time");

                    b.Property<TimeOnly>("StartLocalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_local_time");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.HasKey("Id");

                    b.HasIndex("TechnicianId", "DayOfWeek");

                    b.ToTable("technician_working_hours", "workforce", t =>
                        {
                            t.HasCheckConstraint("ck_technician_working_hours_day_of_week", "day_of_week IN ('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')");

                            t.HasCheckConstraint("ck_technician_working_hours_start_before_end", "end_local_time = '00:00' OR start_local_time < end_local_time");
                        });
                });

            modelBuilder.Entity("CrewCall.Scheduling.Assignments.AssignmentEquipment", b =>
                {
                    b.HasOne("CrewCall.Scheduling.Assignments.Assignment", null)
                        .WithMany("Equipment")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CrewCall.Scheduling.Reservations.ResourceReservation", b =>
                {
                    b.HasOne("CrewCall.Scheduling.Assignments.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Executions.VisitExecution", b =>
                {
                    b.HasOne("CrewCall.WorkOrders.Visits.Visit", null)
                        .WithOne()
                        .HasForeignKey("CrewCall.WorkOrders.Executions.VisitExecution", "VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Executions.VisitExecutionPause", b =>
                {
                    b.HasOne("CrewCall.WorkOrders.Executions.VisitExecution", null)
                        .WithMany("Pauses")
                        .HasForeignKey("VisitExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Incidents.Incident", b =>
                {
                    b.HasOne("CrewCall.WorkOrders.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CrewCall.WorkOrders.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CrewCall.WorkOrders.Sites.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId", "CustomerId")
                        .HasPrincipalKey("Id", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Incidents.IncidentRequiredSkill", b =>
                {
                    b.HasOne("CrewCall.WorkOrders.Incidents.Incident", null)
                        .WithMany("RequiredSkills")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Sites.Site", b =>
                {
                    b.HasOne("CrewCall.WorkOrders.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Visits.Visit", b =>
                {
                    b.HasOne("CrewCall.WorkOrders.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CrewCall.WorkOrders.WorkOrder", b =>
                {
                    b.HasOne("CrewCall.WorkOrders.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CrewCall.WorkOrders.Sites.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId", "CustomerId")
                        .HasPrincipalKey("Id", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CrewCall.Workforce.Absences.TechnicianAbsence", b =>
                {
                    b.HasOne("CrewCall.Workforce.Technicians.Technician", null)
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CrewCall.Workforce.Skills.TechnicianSkill", b =>
                {
                    b.HasOne("CrewCall.Workforce.Skills.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CrewCall.Workforce.Technicians.Technician", null)
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CrewCall.Workforce.Technicians.Technician", b =>
                {
                    b.HasOne("CrewCall.Workforce.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CrewCall.Workforce.WorkingHours.TechnicianWorkingHours", b =>
                {
                    b.HasOne("CrewCall.Workforce.Technicians.Technician", null)
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CrewCall.Scheduling.Assignments.Assignment", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Executions.VisitExecution", b =>
                {
                    b.Navigation("Pauses");
                });

            modelBuilder.Entity("CrewCall.WorkOrders.Incidents.Incident", b =>
                {
                    b.Navigation("RequiredSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
